### ISSUE TITLE
It's compatible with markdown 3.0.1

### ISSUE THREAD

**Issue by neurobin** [jambonrose/markdown_subscript_extension#51]
I see no reason to lock it for Markdown>=2.5,<2.7

**Comment by jambonrose** [comment]
Thanks for the feedback! I'll get a new release out ASAP.

**Comment by jambonrose** [comment]
Following PR #52 , [v2.1 of MarkdownSubscript is available on PyPI](https://pypi.org/project/MarkdownSubscript/2.1.0/).

Please let me know if you have any trouble with the new version!
